# Generated by Django 2.1.15 on 2020-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_user_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('main_text', models.CharField(max_length=300)),
                ('update_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
