# Generated by Django 2.1.15 on 2020-05-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200524_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='main_text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='update_date',
        ),
    ]
