# Generated by Django 2.1.15 on 2020-05-25 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200524_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('photo_1', models.CharField(max_length=200)),
                ('photo_2', models.CharField(max_length=200)),
                ('photo_3', models.CharField(max_length=200)),
                ('tag_1', models.CharField(max_length=10)),
                ('tag_2', models.CharField(max_length=10)),
                ('tag3', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('mail', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmarkarticle',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='bookmarkarticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookmarkcomment',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='bookmarkcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='like',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_circle', to='cms.Circle'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='BookmarkArticle',
        ),
        migrations.DeleteModel(
            name='BookmarkComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
