# Generated by Django 2.1.15 on 2020-05-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200525_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='tag3',
            new_name='tag_3',
        ),
    ]
