# Generated by Django 2.1.15 on 2020-05-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200527_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='circle',
            name='photo_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='circle',
            name='photo_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='circle',
            name='photo_3',
            field=models.CharField(max_length=150),
        ),
    ]
